### ISSUE TITLE
New version of jusText

### ISSUE THREAD

**Issue by miso-belica** [chbrown/justext#1]
Hi, there is new version of [jusText](https://github.com/miso-belica/jusText) library with some improvements. Maybe you can use it instead of this one that is outdated. 

New version also includes working variant of your Unicode flexibility fix. See [changelog](https://github.com/miso-belica/jusText/blob/master/CHANGELOG.rst) (especially incompatible changes) for changes that was made.

Feel free to open an issue or send a PR. Version 2.0 will be also published to PyPi soon.

**Comment by chbrown** [comment]
Cool. Added link in README.
